# =============================================
# graph/state.py
# The shared memory / state of the entire system
# Every agent reads from and writes to this state
# =============================================

from typing import TypedDict, Optional, List
from langchain_core.messages import BaseMessage


class LegalAIState(TypedDict):
    """
    This is the 'brain' of the LangGraph system.
    Every node reads from this state and returns updates to it.

    Fields:
    -------
    user_query       : The original question asked by the user
    query_type       : "rag" | "general" | "task" (set by RouterAgent)
    retrieved_context: The relevant text found in FAISS (set by RAGAgent/TaskAgent)
    agent_response   : The raw answer generated by the agent
    evaluation_result: "pass" | "fail" (set by EvaluatorAgent)
    final_response   : The polished response shown to the user
    messages         : Full conversation history (for multi-turn chat)
    retry_count      : How many times we've retried (max 3)
    """

    user_query: str
    query_type: str
    retrieved_context: Optional[str]
    agent_response: Optional[str]
    evaluation_result: Optional[str]
    final_response: Optional[str]
    messages: List[BaseMessage]
    retry_count: int